ncit:
    doc:
        code: 'NHC0'
        preferredName: 'P108'
        synonym: 'P90'
        synonymTermType: 'P383'
        synonymSource: 'P384'
        synonymCode: 'P385'
        synonymSubSource: 'P386'
        definitionSource: 'P378'
        mapRelation: 'P393'
        mapTarget: 'P395'
        mapTargetTermType: 'P394'
        mapTargetTerminology: 'P396'
        mapTargetTerminologyVersion: 'P397'
        sources: {
            ACC: 'American College of Cardiology',
            "[ACC/AHA]": 'American College of Cardiology / American Heart Association', 
            BIOCARTA: 'BioCarta online maps of molecular pathways, adapted for NCI use',
            BRIDG: 'Biomedical Research Integrated Domain Model Group',
            CADSR: 'Cancer Data Standards Registry and Repository',
            CareLex: 'CareLex electronic Trial Master File Terminology',
            CBDD: 'Chemical Biology and Drug Development',
            CDC: 'U.S. Centers for Disease Control and Prevention',
            CDISC: 'Clinical Data Interchange Standards Consortium',
            CDISC-GLOSS: 'CDISC Glossary Terminology',
            Cellosaurus: 'Cellosaurus - a knowledge resource on cell lines',
            CPTAC: 'Clinical Proteomic Tumor Analysis Consortium',
            COH: 'City of Hope',
            CRCH: 'Cancer Research Center of Hawaii Nutrition Terminology',
            CTCAE: 'Common Terminology Criteria for Adverse Events',
            CTEP: 'Cancer Therapy Evaluation Program',
            CTRM: 'Consortium on Translational Research in the Microbiome',
            CTRP: 'Clinical Trials Reporting Program',
            DCP: 'NCI Division of Cancer Prevention Program',
            DICOM: 'Digital Imaging Communications in Medicine',
            DTP: 'NCI Developmental Therapeutics Program',
            EDQM-HC: 'European Directorate for the Quality of Medicines & Healthcare',
            FDA: 'U.S. Food and Drug Administration',
            GAIA: 'Global Alignment of Immunization safety Assessment in pregnancy Terminology',
            GDC: 'Genomic Data Commons',
            GENC: 'Geopolitical Entities, Names, and Codes Terminology',
            HGNC: 'HUGO Gene Nomenclature Committee',
            HL7: 'Health Level Seven International',
            ICDO3: 'International Classification of Diseases for Oncology, 3rd edition',
            ICDC: 'International Cancer Genome Consortium',
            ICH: 'International Conference on Harmonization',
            INC: 'International Neonatal Consortium',
            IMDRF: 'International Medical Device Regulators Forum',
            JAX: 'Jackson Laboratories Mouse Terminology, adapted for NCI use',
            KEGG: 'KEGG Pathway Database',
            MedDRA: 'Medical Dictionary for Regulatory Activities',
            MMHCC: 'Mouse Models of Human Cancer Consortium',
            NCCN: 'National Comprehensive Cancer Network',
            NCI: 'National Cancer Institute Thesaurus',
            NCI-GLOSS: 'NCI Dictionary of Cancer Terms',
            NCICB: 'NCI Center for Bioinformatics',
            NCI-HL7: 'NCI Health Level 7',
            NCPDP: 'National Council for Prescription Drug Programs',
            NDC: 'National Drug Code',
            NICHD: 'National Institute of Child Health and Human Development',
            PI-RADS: 'Prostate Imaging-Reporting and Data System',
            PID: 'NCI Nature Pathway Interaction Database',
            PQCMC: 'Pharmaceutical Quality/Chemistry, Manufacturing, and Controls',
            RENI: 'Registry Nomenclature Information System',
            SEER: 'Surveillance, Epidemiology, and End Results Program',
            UCUM: 'Unified Code for Units of Measure',
            UMD2001: 'Universal Medical Device Nomenclature System, Version 2001',
            UWDA142: 'University of Washington Digital Anatomist, Version 1.4.2',
            Zebrafish: 'Zebrafish Model Organism Database',
            'ZFin': 'Zebrafish Information Network'        
        }
        termTypes: {
            AB: 'Abbreviation',
            AD: 'Adjectival form (and other parts of grammar)',
            AQ: '*Antiquated preferred term',
            AQS: 'Antiquated term, use when there are antiquated synonyms within a concept',
            BR: 'US brand name, which may be trademarked',
            CA2: 'ISO 3166 alpha-2 country code',
            CA3: 'ISO 3166 alpha-3 country code',
            CNU: 'ISO 3166 numeric country code',
            CI: 'ISO country code',
            CN: 'Drug study code',
            CS: 'US State Department country code',
            DN: 'Display name',
            FB: 'Foreign brand name, which may be trademarked',
            LLT: 'Lower level term',
            HD: '*Header (groups concepts, but not used for coding data)',
            PT: '*Preferred term',
            SN: 'Chemical structure name',
            SY: 'Synonym',                        
        }
#        sourcesToBeRemoved: ['cadsr', 'CADSR', 'CAdsr','caDSR'
#        ]  

